table score_1_metrica_4
	excludeFromModelRefresh
	lineageTag: db388b25-ed1e-4c09-831c-e87429209e1f

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: 289f07c8-4d4e-4b51-b48b-7dfe2d118b96
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column DENOM_SOCIAL
		dataType: string
		lineageTag: dc084ef7-0526-41ae-aa2b-028a48a32eb2
		summarizeBy: none
		sourceColumn: DENOM_SOCIAL

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3b65a8d1-a9f5-4add-b690-b640a417ac15
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: b130f75f-731f-4ed3-b62a-f7bb577ab902
			defaultHierarchy: LocalDateTable_f12401ca-5abe-49a8-8d11-06719d1c196e.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TAB_X_VL_RENTAB_MES
		dataType: double
		lineageTag: 89faad48-4146-4d7d-ab4b-82948428ea01
		summarizeBy: sum
		sourceColumn: TAB_X_VL_RENTAB_MES

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rentabilidade_absoluta
		dataType: double
		lineageTag: 5a096426-ace2-449c-ac86-e52c54003095
		summarizeBy: sum
		sourceColumn: rentabilidade_absoluta

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column metrica_1_4_risco_oculto
		dataType: double
		formatString: 0.00
		lineageTag: 24a8f0d9-d53e-403a-8deb-9f26c67750b9
		summarizeBy: sum
		sourceColumn: metrica_1_4_risco_oculto

		annotation SummarizationSetBy = Automatic

	partition score_1_metrica_4 = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_1_metrica_4",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}, {"TAB_X_VL_RENTAB_MES", type number}, {"rentabilidade_absoluta", type number}, {"metrica_1_4_risco_oculto", Percentage.Type}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

