table score_desvio_desempenho
	lineageTag: 5c2c1262-dcfb-4a37-9013-15fdc30ed42b

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: e8f6ed6f-9e45-4803-82cc-09c9946b5f3c
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column DENOM_SOCIAL
		dataType: string
		lineageTag: c8285f09-071b-4330-9c05-ed8b67ad9a40
		summarizeBy: none
		sourceColumn: DENOM_SOCIAL

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 57407eec-5d65-43c7-b02c-66ee390b7d60
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: c2f4a52a-bf35-478e-a413-ca8b1d33284c
			defaultHierarchy: LocalDateTable_867fe140-d7d8-44c8-ad19-9561c7917a90.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TAB_X_PR_DESEMP_ESPERADO
		dataType: double
		lineageTag: 44c83f96-7082-43a6-b354-abf9f677dbb7
		summarizeBy: sum
		sourceColumn: TAB_X_PR_DESEMP_ESPERADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TAB_X_PR_DESEMP_REAL
		dataType: double
		lineageTag: 23bf8b84-8812-4a53-9f24-59d5e1555b64
		summarizeBy: sum
		sourceColumn: TAB_X_PR_DESEMP_REAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column desvio_desempenho
		dataType: double
		lineageTag: ba23ec9d-208a-4ffe-97c5-bbe6e6b9d2c6
		summarizeBy: none
		sourceColumn: desvio_desempenho

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column metrica_desvio_desempenho
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6fb8b453-6c1c-4785-9f49-87a56068a1a1
		summarizeBy: sum
		sourceColumn: metrica_desvio_desempenho

		annotation SummarizationSetBy = Automatic

	partition score_desvio_desempenho = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_desvio_desempenho",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}, {"metrica_desvio_desempenho", Percentage.Type}, {"desvio_desempenho", Percentage.Type}, {"TAB_X_PR_DESEMP_REAL", type number}, {"TAB_X_PR_DESEMP_ESPERADO", type number}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

