table score_2_metricas_1_e_2
	excludeFromModelRefresh
	lineageTag: ca6b2988-947d-4319-b9bd-9af2147d35fb

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: 9be46e33-5b75-4193-a24a-b79cb86d1a16
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column pct_curto_prazo
		dataType: double
		formatString: 0.00
		lineageTag: 5a0a53fc-cd13-4533-a7c4-c7fe7f26acc1
		summarizeBy: count
		sourceColumn: pct_curto_prazo

		annotation SummarizationSetBy = User

	column pct_longo_prazo
		dataType: double
		formatString: 0.00
		lineageTag: c580c6f0-0bec-4663-b4a7-cd4f90189122
		summarizeBy: sum
		sourceColumn: pct_longo_prazo

		annotation SummarizationSetBy = Automatic

	column PRAZO_PAGTO_RESGATE
		dataType: double
		lineageTag: 0515a9f8-3ac8-4c5a-aec9-5329be20bac3
		summarizeBy: sum
		sourceColumn: PRAZO_PAGTO_RESGATE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column flag_risco_liquidez
		dataType: double
		lineageTag: 7b7f2282-575a-4f54-9aad-66f6bc4340c6
		summarizeBy: sum
		sourceColumn: flag_risco_liquidez

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition score_2_metricas_1_e_2 = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_2_metricas_1_e_2",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"pct_curto_prazo", type number}, {"pct_longo_prazo", type number}, {"PRAZO_PAGTO_RESGATE", type number}, {"flag_risco_liquidez", type number}}),
				    #"Linhas Classificadas" = Table.Sort(#"Tipo Alterado",{{"flag_risco_liquidez", Order.Ascending}})
				in
				    #"Linhas Classificadas"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

