table score_4_metrica_2
	excludeFromModelRefresh
	lineageTag: f1323e17-415b-4972-8418-96a7802f9fa1

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: d25f0364-1472-41c2-b496-270daf856ccc
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9429cf1d-6cf0-4a0a-8eb1-44dc3458af88
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: df5872af-8e5a-4541-baad-3a4cc86bfe56
			defaultHierarchy: LocalDateTable_4adcf974-f005-4cd3-99cd-2ed69f435faf.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column perc_concentracao_cedente
		dataType: string
		lineageTag: 7b4fc007-1247-4ac7-b8ce-7f348ff3c45d
		summarizeBy: none
		sourceColumn: perc_concentracao_cedente

		annotation SummarizationSetBy = Automatic

	column status_alinhamento
		dataType: string
		lineageTag: 5993be34-ec49-4b81-b82f-596c9d0b94ae
		summarizeBy: none
		sourceColumn: status_alinhamento

		annotation SummarizationSetBy = Automatic

	partition score_4_metrica_2 = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_4_metrica_2",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

