table score_prazo_longo
	lineageTag: e99d8213-71ee-4363-9ad9-1c8a0b0614c7

	measure PCT_LONGO_FINAL =
			
			VAR pct =
			    SELECTEDVALUE('score_prazo_longo'[metrica_prazo_longo])
			
			RETURN
			IF(
			    ISINSCOPE('score_prazo_longo'[denom_social]),
			    FORMAT(pct, "0.00%") &
			    IF(pct >= 0.5, " ▲", " ▼"),
			    BLANK()
			)
		lineageTag: e7b259ae-b231-44ea-8f3f-3ba3e852f8c0

	measure Cor_PCT_LONGO =
			
			VAR pct =
			    SELECTEDVALUE('score_prazo_longo'[metrica_prazo_longo])
			
			RETURN
			IF(
			    pct >= 0.5,
			    "#22C55E",
			    "#EF4444"
			)
		lineageTag: 79763c93-e51b-4c75-b8f3-a5ea1311034a

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: 71e9241d-345a-43c0-9f0b-5ce52d1cb66b
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column DENOM_SOCIAL
		dataType: string
		lineageTag: dcc88514-7736-4963-8dd2-819ac58290d4
		summarizeBy: none
		sourceColumn: DENOM_SOCIAL

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2a95ed94-604e-489c-ad7f-17961b14187c
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: a59cf221-bb79-4604-8fcf-3c1068ac3883
			defaultHierarchy: LocalDateTable_aa39cf99-27b4-4943-a694-09925df6b897.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TAB_V_A_VL_DIRCRED_PRAZO
		dataType: decimal
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: d3f6edf5-45e9-48de-a671-4c1b1cfc4efe
		summarizeBy: sum
		sourceColumn: TAB_V_A_VL_DIRCRED_PRAZO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column prazo_longo
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 66284a22-8477-4988-89af-f392d192608d
		summarizeBy: sum
		sourceColumn: prazo_longo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column metrica_prazo_longo
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 62fff4ff-0da9-4728-9c01-344ca358c603
		summarizeBy: sum
		sourceColumn: metrica_prazo_longo

		annotation SummarizationSetBy = Automatic

	partition score_prazo_longo = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_prazo_longo",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}, {"TAB_V_A_VL_DIRCRED_PRAZO", Currency.Type}, {"prazo_longo", Currency.Type}, {"metrica_prazo_longo", Percentage.Type}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

