table score_3_metrica_1
	excludeFromModelRefresh
	lineageTag: 74adb961-0d75-4faf-9eb0-b65118c43b4c

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: 5491b8bc-19cf-4995-93da-0ee5accdb5f5
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 78ace51d-b0ff-4aa0-beb7-37fcbf42dc88
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: 69f64161-af79-4ecd-b501-3dc4cfc13146
			defaultHierarchy: LocalDateTable_b7ba6510-d466-44da-9a5b-c499f005d4d8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column HHI_Cedentes
		dataType: double
		lineageTag: 1979516f-799b-458f-8eaf-7051506e3d4e
		summarizeBy: sum
		sourceColumn: HHI_Cedentes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column score_cedentes
		dataType: double
		lineageTag: ed169a36-ddee-441e-8e94-a34323e9f8c9
		summarizeBy: sum
		sourceColumn: score_cedentes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column score_100
		dataType: double
		lineageTag: a8d71168-2d7c-4412-90e2-33edbb0905f9
		summarizeBy: sum
		sourceColumn: score_100

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition score_3_metrica_1 = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_3_metrica_1",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}, {"HHI_Cedentes", type number}, {"score_cedentes", type number}, {"score_100", type number}})
				in
				    #"Tipo Alterado"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

