table score_1_metrica_2
	excludeFromModelRefresh
	lineageTag: c39fbc15-7e15-406d-8736-5a952654d29c

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: 62ea8681-7ac1-482e-8788-c05c09fcecfd
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column DENOM_SOCIAL
		dataType: string
		lineageTag: 36953aa6-ecab-46ab-a71b-247cacb1d879
		summarizeBy: none
		sourceColumn: DENOM_SOCIAL

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 08ddcdd5-f9a9-434e-9d5e-cbd7bbf02929
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: 25ea6c9d-4c63-4c4d-a839-0e328cacffc1
			defaultHierarchy: LocalDateTable_93071ed8-b7f6-4189-9699-b6140034ac69.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TAB_I2_VL_CARTEIRA
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: e15f46b6-18df-4c29-81b3-c354156a31e7
		summarizeBy: sum
		sourceColumn: TAB_I2_VL_CARTEIRA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column TAB_I2A5_VL_CRED_VENCIDO_PENDENTE
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 2d55bfed-a38f-4abd-a97f-1bf3833b3797
		summarizeBy: sum
		sourceColumn: TAB_I2A5_VL_CRED_VENCIDO_PENDENTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column TAB_I2A6_VL_CRED_EMP_RECUP
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: fa22fefe-18cc-4a77-8ca2-4426ec2fb043
		summarizeBy: sum
		sourceColumn: TAB_I2A6_VL_CRED_EMP_RECUP

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column distressed_total
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 8e01f132-790d-417d-b44e-b74be1ca692f
		summarizeBy: sum
		sourceColumn: distressed_total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column metrica_1_2_estrategia_distressed
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2896eda0-5060-4285-8744-5011c1c56998
		summarizeBy: sum
		sourceColumn: metrica_1_2_estrategia_distressed

		annotation SummarizationSetBy = Automatic

	partition score_1_metrica_2 = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_1_metrica_2",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}, {"TAB_I2_VL_CARTEIRA", Currency.Type}, {"TAB_I2A5_VL_CRED_VENCIDO_PENDENTE", Currency.Type}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Tipo Alterado", {{"TAB_I2_VL_CARTEIRA", type text}}, "pt-BR"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade",{{"TAB_I2_VL_CARTEIRA", Currency.Type}, {"TAB_I2A6_VL_CRED_EMP_RECUP", Currency.Type}, {"distressed_total", Currency.Type}, {"metrica_1_2_estrategia_distressed", Percentage.Type}})
				in
				    #"Tipo Alterado1"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

