table score_1_metrica_1
	excludeFromModelRefresh
	lineageTag: 025b6ea7-9336-4932-95b1-36670bed6ab8

	measure Medida = ```
			{
			  "name": "Superstore Dashboard - Remi Rouquette",
			  "dataColors": [
			    "#378ADD",
			    "#1D9E75",
			    "#7F77DD",
			    "#EF9F27",
			    "#D85A30",
			    "#E24B4A",
			    "#888780",
			    "#5DCAA5"
			  ],
			  "background": "#13151a",
			  "foreground": "#1c1f2a",
			  "tableAccent": "#378ADD",
			  "good": "#1D9E75",
			  "neutral": "#EF9F27",
			  "bad": "#E24B4A",
			  "maximum": "#1D9E75",
			  "center": "#EF9F27",
			  "minimum": "#E24B4A",
			  "null": "#2d3140",
			  "textClasses": {
			    "callout": {
			      "fontSize": 22,
			      "fontFace": "Segoe UI",
			      "color": "#f0f2f5"
			    },
			    "title": {
			      "fontSize": 13,
			      "fontFace": "Segoe UI",
			      "color": "#f0f2f5"
			    },
			    "header": {
			      "fontSize": 11,
			      "fontFace": "Segoe UI",
			      "color": "#9ca3af"
			    },
			    "label": {
			      "fontSize": 10,
			      "fontFace": "Segoe UI",
			      "color": "#6b7280"
			    }
			  },
			  "visualStyles": {
			    "*": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "border": [{
			          "show": true,
			          "color": { "solid": { "color": "#2d3140" } },
			          "radius": 8
			        }],
			        "shadow": [{
			          "show": true,
			          "color": { "solid": { "color": "#000000" } },
			          "position": "BottomRight",
			          "preset": "Custom",
			          "transparency": 80,
			          "blur": 10
			        }]
			      }
			    },
			    "card": {
			      "*": {
			        "labels": [{
			          "color": { "solid": { "color": "#f0f2f5" } },
			          "fontSize": 12,
			          "fontFamily": "Segoe UI",
			          "bold": true,
			          "labelDisplayUnits": 0,
			          "labelPrecision": 2
			        }],
			        "categoryLabels": [{
			          "show": false
			        }],
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }]
			      }
			    },
			    "lineChart": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "valueAxis": [{
			          "gridlineColor": { "solid": { "color": "#2d3140" } },
			          "labelColor": { "solid": { "color": "#6b7280" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false,
			          "labelDisplayUnits": 1
			        }],
			        "categoryAxis": [{
			          "labelColor": { "solid": { "color": "#6b7280" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false,
			          "gridlineColor": { "solid": { "color": "#2d3140" } },
			          "gridlineThickness": 1
			        }],
			        "legend": [{
			          "labelColor": { "solid": { "color": "#9ca3af" } }
			        }],
			        "markers": [{
			          "show": true,
			          "size": 3
			        }],
			        "lineStyles": [{
			          "areaShow": true,
			          "showMarker": true,
			          "markerSize": 3
			        }]
			      }
			    },
			    "barChart": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "valueAxis": [{
			          "gridlineColor": { "solid": { "color": "#2d3140" } },
			          "labelColor": { "solid": { "color": "#6b7280" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false,
			          "labelDisplayUnits": 1
			        }],
			        "categoryAxis": [{
			          "labelColor": { "solid": { "color": "#9ca3af" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false,
			          "gridlineColor": { "solid": { "color": "#2d3140" } },
			          "gridlineThickness": 1
			        }]
			      }
			    },
			    "columnChart": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "valueAxis": [{
			          "gridlineColor": { "solid": { "color": "#2d3140" } },
			          "labelColor": { "solid": { "color": "#6b7280" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false,
			          "labelDisplayUnits": 1
			        }],
			        "categoryAxis": [{
			          "labelColor": { "solid": { "color": "#9ca3af" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false,
			          "gridlineColor": { "solid": { "color": "#2d3140" } }
			        }]
			      }
			    },
			    "scatterChart": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "valueAxis": [{
			          "gridlineColor": { "solid": { "color": "#2d3140" } },
			          "labelColor": { "solid": { "color": "#6b7280" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false
			        }],
			        "categoryAxis": [{
			          "labelColor": { "solid": { "color": "#6b7280" } },
			          "titleColor": { "solid": { "color": "#6b7280" } },
			          "showAxisTitle": false
			        }]
			      }
			    },
			    "donutChart": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "legend": [{
			          "labelColor": { "solid": { "color": "#9ca3af" } }
			        }]
			      }
			    },
			    "filledMap": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "legend": [{
			          "labelColor": { "solid": { "color": "#9ca3af" } }
			        }]
			      }
			    },
			    "actionButton": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "fill": [{
			          "show": true,
			          "fillColor": { "solid": { "color": "#1c1f2a" } },
			          "transparency": 0
			        }],
			        "outline": [{
			          "show": true,
			          "weight": 1
			        }],
			        "shadow": [{
			          "show": true,
			          "blur": 5,
			          "position": "Custom",
			          "distance": 20
			        }],
			        "text": [{
			          "show": true,
			          "bold": true,
			          "fontColor": { "solid": { "color": "#f0f2f5" } },
			          "fontFamily": "Segoe UI",
			          "fontSize": 11
			        }],
			        "shape": [{
			          "roundEdge": 5
			        }]
			      }
			    },
			    "slicer": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#1c1f2a" } }
			        }],
			        "data": [{
			          "fontColor": { "solid": { "color": "#9ca3af" } },
			          "backgroundColor": { "solid": { "color": "#1c1f2a" } },
			          "fontFamily": "Segoe UI",
			          "fontSize": 11
			        }],
			        "header": [{
			          "fontColor": { "solid": { "color": "#6b7280" } },
			          "backgroundColor": { "solid": { "color": "#1c1f2a" } },
			          "outline": "None",
			          "fontFamily": "Segoe UI",
			          "fontSize": 11
			        }],
			        "items": [{
			          "fontColor": { "solid": { "color": "#9ca3af" } },
			          "background": { "solid": { "color": "#1c1f2a" } }
			        }]
			      }
			    },
			    "textbox": {
			      "*": {
			        "background": [{
			          "color": { "solid": { "color": "#13151a" } }
			        }]
			      }
			    }
			  }
			}
			
			```
		lineageTag: fd0823b2-0c06-45f6-a858-6675ccbb0fd9

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: 3a92e4f4-e2f1-47cf-90fe-60de7b4e8d35
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		annotation SummarizationSetBy = Automatic

	column DENOM_SOCIAL
		dataType: string
		lineageTag: 25c00575-c3a5-4af2-a201-4ee1f30f3f38
		summarizeBy: none
		sourceColumn: DENOM_SOCIAL

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0d8c3466-1899-4c3c-8d5b-543d6ebb35fb
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: 78a16460-57df-4660-8fb2-3d9002c99ded
			defaultHierarchy: LocalDateTable_c801aff6-1724-4a4d-84c1-abb6b63eca68.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TAB_I2_VL_CARTEIRA
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: fee11d10-4726-489f-aad1-de98fcd5501e
		summarizeBy: sum
		sourceColumn: TAB_I2_VL_CARTEIRA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column TAB_I2A3_VL_CRED_INAD
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: b3c9aefe-80b0-493b-ae7e-246b13e52ba3
		summarizeBy: sum
		sourceColumn: TAB_I2A3_VL_CRED_INAD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column metrica_1_1_taxa_inadimplencia_atual
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 377bb203-4d78-4534-b02a-f6602c573667
		summarizeBy: average
		sourceColumn: metrica_1_1_taxa_inadimplencia_atual

		annotation SummarizationSetBy = User

	partition score_1_metrica_1 = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_1_metrica_1",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}, {"TAB_I2_VL_CARTEIRA", Currency.Type}, {"TAB_I2A3_VL_CRED_INAD", Currency.Type}, {"metrica_1_1_taxa_inadimplencia_atual", Percentage.Type}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Tipo Alterado", {{"TAB_I2_VL_CARTEIRA", Currency.Type}}, "pt-BR")
				in
				    #"Tipo Alterado com Localidade"
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

