table score_1_metrica_3
	excludeFromModelRefresh
	lineageTag: d55ded67-0cd4-4462-a69c-b232b3664cf1

	column CNPJ_FUNDO_CLASSE
		dataType: string
		lineageTag: b78b8e60-9a5d-44e8-8e93-b5e8cc797bd2
		summarizeBy: none
		sourceColumn: CNPJ_FUNDO_CLASSE

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DENOM_SOCIAL
		dataType: string
		lineageTag: e6055450-a4c7-4d8b-8a13-a4c309ba236b
		summarizeBy: none
		sourceColumn: DENOM_SOCIAL

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DT_COMPTC
		dataType: dateTime
		formatString: Long Date
		lineageTag: 846924ea-6a4d-4e77-9d63-634bb337d771
		summarizeBy: none
		sourceColumn: DT_COMPTC

		variation Variation
			isDefault
			relationship: 55d3fc3b-11ee-4f65-8f2c-d20a9390b31d
			defaultHierarchy: LocalDateTable_9957131b-4e77-40ff-9008-562308e1a608.'Hierarquia de datas'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TAB_I2_VL_CARTEIRA
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: afe70278-807d-45e4-90d3-7d4fa5e030fb
		summarizeBy: sum
		sourceColumn: TAB_I2_VL_CARTEIRA

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column TAB_X_VL_GARANTIA_DIRCRED
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 22a58166-c6e9-4cd6-b988-10cafbd89ec6
		summarizeBy: sum
		sourceColumn: TAB_X_VL_GARANTIA_DIRCRED

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column TAB_X_PR_GARANTIA_DIRCRED
		dataType: double
		lineageTag: 9968c757-2e4a-4b4c-9ca2-4e033daea86f
		summarizeBy: sum
		sourceColumn: TAB_X_PR_GARANTIA_DIRCRED

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column metrica_1_3_nivel_garantia_coobrigacao
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e41e0675-42e1-41ff-8866-9da25c56996b
		summarizeBy: sum
		sourceColumn: metrica_1_3_nivel_garantia_coobrigacao

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition score_1_metrica_3 = m
		mode: import
		source = ```
				let
				    // URL do Supabase + o caminho da tabela
				    UrlDaApi = "https://bgkrnjbleagxnhjlggbj.supabase.co/rest/v1/score_1_metrica_3",
				    
				    // Chave anon public (coloque a mesma chave nos dois lugares)
				    ChaveAnon = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJna3JuamJsZWFneG5oamxnZ2JqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3NjYxNTEsImV4cCI6MjA5MTM0MjE1MX0.i2ZIZHy74lfohzGf-YCFiRduLT3yWzPZWVYXaOY9Qhg",
				
				    Fonte = Json.Document(Web.Contents(UrlDaApi, 
				        [Headers=[apikey=ChaveAnon, Authorization="Bearer " & ChaveAnon]]
				    )),
				    
				    // Converte a resposta da API (JSON) em uma tabela legível
				    Tabela = Table.FromRecords(Fonte),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Tabela,{{"DT_COMPTC", type date}, {"TAB_I2_VL_CARTEIRA", Currency.Type}, {"TAB_X_VL_GARANTIA_DIRCRED", Currency.Type}, {"TAB_X_PR_GARANTIA_DIRCRED", type number}, {"metrica_1_3_nivel_garantia_coobrigacao", Percentage.Type}})
				in
				    #"Tipo Alterado"
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

